server:
  port: 8083
spring:
  application:
    name: msg-kafka-consumer
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: myGroup
eureka:
  instance:
    instance-id: msg-kafka-consumer
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
my:
  netty:
    host: eureka-tcp-server
    port: 9000