version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: 'zookeeper'
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: if netstat -ltn | grep -c "2181"; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 2
  kafka:
    image: bitnami/kafka:latest
    container_name: 'kafka'
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    healthcheck:
      test: if netstat -ltn | grep -c "9092"; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 2
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
