version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    healthcheck:
      test: if netstat -ltn | grep -c "2181"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 20s
      timeout: 5s
      retries: 3
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: if netstat -ltn | grep -c "90912"; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 3
  eureka-server:
    image: 'eheh12321/eureka-server'
    container_name: 'eureka-server'
    ports:
      - '8761:8761'
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: if netstat -ltn | grep -c "8761"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
  eureka-gateway:
    image: 'eheh12321/eureka-gateway'
    container_name: 'eureka-gateway'
    ports:
      - '8000:8000'
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: if netstat -ltn | grep -c "8000"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
  eureka-kafka-producer:
    image: 'eheh12321/eureka-kafka-producer'
    container_name: 'eureka-kafka-producer'
    ports:
      - '8082:8082'
    healthcheck:
      test: if netstat -ltn | grep -c "8082"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      eureka-gateway:
        condition: service_healthy
  eureka-tcp-server:
    image: 'eheh12321/eureka-tcp-server'
    container_name: 'eureka-tcp-server'
    ports:
      - '8085:8085'
    healthcheck:
      test: if netstat -ltn | grep -c "8085"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
  eureka-kafka-consumer:
    image: 'eheh12321/eureka-kafka-consumer'
    container_name: 'eureka-kafka-consumer'
    ports:
      - '8083:8083'
    healthcheck:
      test: if netstat -ltn | grep -c "8083"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - eureka-gateway
      - eureka-tcp-server
