version: "3"
services:
  eureka-server:
    image: 'eheh12321/eureka-server'
    container_name: 'eureka-server'
    ports:
      - '8761:8761'
    healthcheck: 
      test: if netstat -ltn | grep -c "8761"; then echo 0; else echo 1; fi
      interval: 10s
      timeout: 5s
      retries: 2

  eureka-gateway:
    image: 'eheh12321/eureka-gateway'
    container_name: 'eureka-gateway'
    ports:
      - '8000:8000'
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: if netstat -ltn | grep -c "8000"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 2
  
  eureka-kafka-producer:
    image: 'eheh12321/eureka-kafka-producer'
    container_name: 'eureka-kafka-producer'
    ports:
      - '8082:8082'
    healthcheck:
      test: if netstat -ltn | grep -c "8082"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 2
    depends_on:
      eureka-gateway:
        condition: service_healthy
  
  eureka-tcp-server:
    image: 'eheh12321/eureka-tcp-server'
    container_name: 'eureka-tcp-server'
    ports:
      - '8085:8085'
    healthcheck:
      test: if netstat -ltn | grep -c "8085"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 2
  
  eureka-kafka-consumer:
    image: 'eheh12321/eureka-kafka-consumer'
    container_name: 'eureka-kafka-consumer'
    ports:
      - '8083:8083'
    healthcheck:
      test: if netstat -ltn | grep -c "8083"; then echo 0; else echo 1; fi # 0: Success, 1: Unhealthy
      interval: 10s
      timeout: 5s
      retries: 2
    depends_on:
      - eureka-gateway
      - eureka-tcp-server

