server:
  port: 8000
  servlet:
    context-path: /
eureka:
  instance:
    instance-id: gateway-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /send/api-docs
        name: Kafka producer
        display-name: kafka producer (8082)
jwt:
  secretKey: qweqweqwe123123123qweqweqwe123123123qweqweqwe123123123qweqweqwe123123123qweqweqwe123123123qweqweqwe123123123

---

spring:
  config:
    activate:
      on-profile: docker
eureka:
  clients:
    service-url:
      defaultZone: http://eureka-server:8761/eureka