server:
  port: 8085
spring:
  application:
    name: tcp-server
eureka:
  instance:
    instance-id: tcp-server
  clients:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: docker
eureka:
  clients:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
